In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df_original = pd.read_csv('training_data.csv')
df_original.head()

Red   Green   Blue     NIR      ndvi      ndwi    msavi2     mtvi2  \
0  1376.0  1150.0  795.0  2598.0  0.307499 -0.386339  0.470314  0.338574   
1  1342.0  1101.0  776.0  2676.0  0.332006 -0.416998  0.498459  0.360913   
2  1347.0  1101.0  785.0  2671.0  0.329517 -0.416225  0.495648  0.356393   
3  1303.0  1140.0  722.0  2628.0  0.337064 -0.394904  0.504138  0.393367   
4  1358.0  1141.0  727.0  2758.0  0.340136 -0.414722  0.507569  0.380207   

       vari      tgi  Class  
0 -0.130560  13390.0      0  
1 -0.144571  11065.0      0  
2 -0.147925  10350.0      0  
3 -0.094712  19375.0      0  
4 -0.122460  17245.0      0

In [30]:
df_original

Red   Green    Blue     NIR      ndvi      ndwi    msavi2     mtvi2  \
0      1376.0  1150.0   795.0  2598.0  0.307499 -0.386339  0.470314  0.338574   
1      1342.0  1101.0   776.0  2676.0  0.332006 -0.416998  0.498459  0.360913   
2      1347.0  1101.0   785.0  2671.0  0.329517 -0.416225  0.495648  0.356393   
3      1303.0  1140.0   722.0  2628.0  0.337064 -0.394904  0.504138  0.393367   
4      1358.0  1141.0   727.0  2758.0  0.340136 -0.414722  0.507569  0.380207   
...       ...     ...     ...     ...       ...       ...       ...       ...   
48137  2493.0  2214.0  1764.0  2726.0  0.044645 -0.103644  0.085459 -0.022867   
48138  2517.0  2298.0  1835.0  2722.0  0.039130 -0.084462  0.075299 -0.010665   
48139  2452.0  2291.0  1868.0  2724.0  0.052550 -0.086341  0.099837  0.032247   
48140  2285.0  2130.0  1642.0  2595.0  0.063525 -0.098413  0.119440  0.049287   
48141  2371.0  2207.0  1749.0  2678.0  0.060804 -0.096418  0.114619  0.043473   

           vari      tgi  Class  
0     -0.130560  13390.0      0  
1     -0.144571  11065.0      0  
2     -0.147925  10350.0      0  
3     -0.094712  19375.0      0  
4     -0.122460  17245.0      0  
...         ...      ...    ...  
48137 -0.094801  17235.0      2  
48138 -0.073490  20115.0      2  
48139 -0.056000  19745.0      2  
48140 -0.055896  23855.0      2  
48141 -0.057971  21740.0      2  

[48142 rows x 11 columns]

In [8]:
df_original.isnull().sum()

Red       0
Green     0
Blue      0
NIR       0
ndvi      0
ndwi      0
msavi2    0
mtvi2     0
vari      0
tgi       0
Class     0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48142 entries, 0 to 48141
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Red     48142 non-null  float64
 1   Green   48142 non-null  float64
 2   Blue    48142 non-null  float64
 3   NIR     48142 non-null  float64
 4   ndvi    48142 non-null  float64
 5   ndwi    48142 non-null  float64
 6   msavi2  48142 non-null  float64
 7   mtvi2   48142 non-null  float64
 8   vari    48142 non-null  float64
 9   tgi     48142 non-null  float64
 10  Class   48142 non-null  int64  
dtypes: float64(10), int64(1)
memory usage: 4.0 MB


In [17]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Identify numeric features (excluding the 'Class' column)
features = df_original.columns.difference(['Class'])

# ===== Figure 1: Normal Distributions =====

# Create a figure with subplots for normal distributions
plt.figure(figsize=(15, 10))
df[features].hist(figsize=(15, 10), bins=30)
plt.tight_layout()
plt.savefig('normal_feature_distributions.png')
plt.close()

# ===== Figure 2: Log Transformed Distributions =====

# Create a copy of the DataFrame to apply log transformation
df_log = df_original.copy()

# Apply log transformation with shifting to each feature
for column in features:
    min_value = df_log[column].min()
    if min_value <= 0:
        shift = abs(min_value) + 1  # Shift all values by |min_value| + 1
        df_log[column] = np.log(df_log[column] + shift)
    else:
        df_log[column] = np.log(df_log[column])

# Create a figure with subplots for log-transformed distributions
plt.figure(figsize=(15, 10))
df_log[features].hist(figsize=(15, 10), bins=30)
plt.tight_layout()
plt.savefig('log_transformed_feature_distributions.png')
plt.close()


<Figure size 1500x1000 with 0 Axes>

<Figure size 1500x1000 with 0 Axes>

In [22]:
from sklearn.model_selection import train_test_split
import numpy as np

df=df_original.copy()

# Assume df is your original DataFrame
X_normal = df.drop(columns=['Class'])  # Normal Data Features
y_normal = df['Class']  # Labels

# ===== Step 1: Split Normal Data =====
# First split for Normal Data (Training 70%, Temp 30%)
X_train_normal, X_temp_normal, y_train_normal, y_temp_normal = train_test_split(X_normal, y_normal, test_size=0.3, stratify=y_normal, random_state=42)

# Second split for Normal Data (Validation 15%, Test 15%)
X_val_normal, X_test_normal, y_val_normal, y_test_normal = train_test_split(X_temp_normal, y_temp_normal, test_size=0.5, stratify=y_temp_normal, random_state=42)

# ===== Step 2: Log Transformation =====
# Log-Transform the data (with shifting to handle non-positive values)
df_log = df.copy()
features = df.columns.difference(['Class'])

for column in features:
    min_value = df_log[column].min()
    if min_value <= 0:
        shift = abs(min_value) + 1
        df_log[column] = np.log(df_log[column] + shift)
    else:
        df_log[column] = np.log(df_log[column])

X_log = df_log.drop(columns=['Class'])  # Log-Transformed Data Features
y_log = df_log['Class']  # Labels (same as original)

# ===== Step 3: Split Log-Transformed Data =====
# First split for Log-Transformed Data (Training 70%, Temp 30%)
X_train_log, X_temp_log, y_train_log, y_temp_log = train_test_split(X_log, y_log, test_size=0.3, stratify=y_log, random_state=42)

# Second split for Log-Transformed Data (Validation 15%, Test 15%)
X_val_log, X_test_log, y_val_log, y_test_log = train_test_split(X_temp_log, y_temp_log, test_size=0.5, stratify=y_temp_log, random_state=42)


In [36]:
import numpy as np
from sklearn.model_selection import train_test_split
df=df_original.copy()

# List of features to log-transform
log_features = ['Blue', 'Green', 'NIR', 'Red']  # Adjust based on your column names
normal_features = df.columns.difference(['Class', 'Blue', 'Green', 'NIR', 'Red'])

# Create a copy of the DataFrame
df_mixed = df.copy()

# Apply log transformation to the selected features
for column in log_features:
    min_value = df_mixed[column].min()
    if min_value <= 0:
        shift = abs(min_value) + 1  # Shift values if any non-positive numbers are present
        df_mixed[column] = np.log(df_mixed[column] + shift)
    else:
        df_mixed[column] = np.log(df_mixed[column])

# Now df_mixed contains log-transformed 'Blue', 'Green', 'NIR', 'Red' and normal rest
# Features (X) and target (y)
X_mixed = df_mixed.drop(columns=['Class'])  # Mixed (log and normal) features
y_mixed = df_mixed['Class']  # Labels

# First split: Training set (70%) and temp set (30%)
X_train_mixed, X_temp_mixed, y_train_mixed, y_temp_mixed = train_test_split(X_mixed, y_mixed, test_size=0.3, stratify=y_mixed, random_state=42)

# Second split: Validation (15%) and Test (15%) from the temp set
X_val_mixed, X_test_mixed, y_val_mixed, y_test_mixed = train_test_split(X_temp_mixed, y_temp_mixed, test_size=0.5, stratify=y_temp_mixed, random_state=42)


In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Train Random Forest on Normal Data
model_normal = RandomForestClassifier(random_state=42)
model_normal.fit(X_train_normal, y_train_normal)

# Evaluate on Validation Set
y_pred_val_normal = model_normal.predict(X_val_normal)
print("Normal Data - Validation Set Evaluation")
print(confusion_matrix(y_val_normal, y_pred_val_normal))
print(classification_report(y_val_normal, y_pred_val_normal))

# Evaluate on Test Set
y_pred_test_normal = model_normal.predict(X_test_normal)
print("Normal Data - Test Set Evaluation")
print(confusion_matrix(y_test_normal, y_pred_test_normal))
print(classification_report(y_test_normal, y_pred_test_normal))


Normal Data - Validation Set Evaluation
[[1034    0    7]
 [   0 3833    0]
 [   3    0 2344]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221

Normal Data - Test Set Evaluation
[[1040    0    1]
 [   0 3833    0]
 [   4    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [24]:
# Train Random Forest on Log-Transformed Data
model_log = RandomForestClassifier(random_state=42)
model_log.fit(X_train_log, y_train_log)

# Evaluate on Validation Set
y_pred_val_log = model_log.predict(X_val_log)
print("Log-Transformed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_log, y_pred_val_log))
print(classification_report(y_val_log, y_pred_val_log))

# Evaluate on Test Set
y_pred_test_log = model_log.predict(X_test_log)
print("Log-Transformed Data - Test Set Evaluation")
print(confusion_matrix(y_test_log, y_pred_test_log))
print(classification_report(y_test_log, y_pred_test_log))


Log-Transformed Data - Validation Set Evaluation
[[1034    0    7]
 [   0 3833    0]
 [   3    0 2344]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221

Log-Transformed Data - Test Set Evaluation
[[1040    0    1]
 [   0 3833    0]
 [   4    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Train Random Forest on the mixed (log and normal) data
model_mixed = RandomForestClassifier(random_state=42)
model_mixed.fit(X_train_mixed, y_train_mixed)

# Evaluate on Validation Set
y_pred_val_mixed = model_mixed.predict(X_val_mixed)
print("Mixed Data (Log for Blue, Green, NIR, Red) - Validation Set Evaluation")
print(confusion_matrix(y_val_mixed, y_pred_val_mixed))
print(classification_report(y_val_mixed, y_pred_val_mixed))

# Evaluate on Test Set
y_pred_test_mixed = model_mixed.predict(X_test_mixed)
print("Mixed Data (Log for Blue, Green, NIR, Red) - Test Set Evaluation")
print(confusion_matrix(y_test_mixed, y_pred_test_mixed))
print(classification_report(y_test_mixed, y_pred_test_mixed))


Mixed Data (Log for Blue, Green, NIR, Red) - Validation Set Evaluation
[[1034    0    7]
 [   0 3833    0]
 [   3    0 2344]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221

Mixed Data (Log for Blue, Green, NIR, Red) - Test Set Evaluation
[[1040    0    1]
 [   0 3833    0]
 [   4    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00    

In [41]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Scale the data
scaler = StandardScaler()
X_train_normal_scaled = scaler.fit_transform(X_train_normal)
X_val_normal_scaled = scaler.transform(X_val_normal)
X_test_normal_scaled = scaler.transform(X_test_normal)

# Train Logistic Regression on scaled normal data
model_lr_normal = LogisticRegression(random_state=42, max_iter=1000)
model_lr_normal.fit(X_train_normal_scaled, y_train_normal)

# Evaluate on Validation Set
y_pred_val_lr_normal = model_lr_normal.predict(X_val_normal_scaled)
print("Logistic Regression - Scaled Normal Data - Validation Set Evaluation")
print(confusion_matrix(y_val_normal, y_pred_val_lr_normal))
print(classification_report(y_val_normal, y_pred_val_lr_normal))

# Evaluate on Test Set
y_pred_test_lr_normal = model_lr_normal.predict(X_test_normal_scaled)
print("Logistic Regression - Scaled Normal Data - Test Set Evaluation")
print(confusion_matrix(y_test_normal, y_pred_test_lr_normal))
print(classification_report(y_test_normal, y_pred_test_lr_normal))


Logistic Regression - Scaled Normal Data - Validation Set Evaluation
[[1030    0   11]
 [   0 3833    0]
 [  14    3 2330]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1041
           1       1.00      1.00      1.00      3833
           2       1.00      0.99      0.99      2347

    accuracy                           1.00      7221
   macro avg       0.99      0.99      0.99      7221
weighted avg       1.00      1.00      1.00      7221

Logistic Regression - Scaled Normal Data - Test Set Evaluation
[[1036    0    5]
 [   0 3833    0]
 [  10    0 2338]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      72

In [42]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Scale the log-transformed data
scaler_log = StandardScaler()
X_train_log_scaled = scaler_log.fit_transform(X_train_log)
X_val_log_scaled = scaler_log.transform(X_val_log)
X_test_log_scaled = scaler_log.transform(X_test_log)

# Train Logistic Regression on scaled log-transformed data
model_lr_log = LogisticRegression(random_state=42, max_iter=1000)
model_lr_log.fit(X_train_log_scaled, y_train_log)

# Evaluate on Validation Set
y_pred_val_lr_log = model_lr_log.predict(X_val_log_scaled)
print("Logistic Regression - Scaled Log-Transformed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_log, y_pred_val_lr_log))
print(classification_report(y_val_log, y_pred_val_lr_log))

# Evaluate on Test Set
y_pred_test_lr_log = model_lr_log.predict(X_test_log_scaled)
print("Logistic Regression - Scaled Log-Transformed Data - Test Set Evaluation")
print(confusion_matrix(y_test_log, y_pred_test_lr_log))
print(classification_report(y_test_log, y_pred_test_lr_log))


Logistic Regression - Scaled Log-Transformed Data - Validation Set Evaluation
[[1031    0   10]
 [   0 3833    0]
 [  14    6 2327]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1041
           1       1.00      1.00      1.00      3833
           2       1.00      0.99      0.99      2347

    accuracy                           1.00      7221
   macro avg       0.99      0.99      0.99      7221
weighted avg       1.00      1.00      1.00      7221

Logistic Regression - Scaled Log-Transformed Data - Test Set Evaluation
[[1035    0    6]
 [   0 3833    0]
 [   9    0 2339]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00

In [43]:
# Scale the mixed data (some features log-transformed, some normal)
scaler_mixed = StandardScaler()
X_train_mixed_scaled = scaler_mixed.fit_transform(X_train_mixed)
X_val_mixed_scaled = scaler_mixed.transform(X_val_mixed)
X_test_mixed_scaled = scaler_mixed.transform(X_test_mixed)

# Train Logistic Regression on scaled mixed data
model_lr_mixed = LogisticRegression(random_state=42, max_iter=1000)
model_lr_mixed.fit(X_train_mixed_scaled, y_train_mixed)

# Evaluate on Validation Set
y_pred_val_lr_mixed = model_lr_mixed.predict(X_val_mixed_scaled)
print("Logistic Regression - Scaled Mixed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_mixed, y_pred_val_lr_mixed))
print(classification_report(y_val_mixed, y_pred_val_lr_mixed))

# Evaluate on Test Set
y_pred_test_lr_mixed = model_lr_mixed.predict(X_test_mixed_scaled)
print("Logistic Regression - Scaled Mixed Data - Test Set Evaluation")
print(confusion_matrix(y_test_mixed, y_pred_test_lr_mixed))
print(classification_report(y_test_mixed, y_pred_test_lr_mixed))


Logistic Regression - Scaled Mixed Data - Validation Set Evaluation
[[1029    0   12]
 [   0 3833    0]
 [  14    5 2328]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1041
           1       1.00      1.00      1.00      3833
           2       0.99      0.99      0.99      2347

    accuracy                           1.00      7221
   macro avg       0.99      0.99      0.99      7221
weighted avg       1.00      1.00      1.00      7221

Logistic Regression - Scaled Mixed Data - Test Set Evaluation
[[1035    0    6]
 [   0 3833    0]
 [  10    0 2338]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222

In [44]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Scale the normal data
scaler = StandardScaler()
X_train_normal_scaled = scaler.fit_transform(X_train_normal)
X_val_normal_scaled = scaler.transform(X_val_normal)
X_test_normal_scaled = scaler.transform(X_test_normal)

# Train SVM on scaled normal data
model_svm_normal = SVC(random_state=42)
model_svm_normal.fit(X_train_normal_scaled, y_train_normal)

# Evaluate on Validation Set
y_pred_val_svm_normal = model_svm_normal.predict(X_val_normal_scaled)
print("SVM - Scaled Normal Data - Validation Set Evaluation")
print(confusion_matrix(y_val_normal, y_pred_val_svm_normal))
print(classification_report(y_val_normal, y_pred_val_svm_normal))

# Evaluate on Test Set
y_pred_test_svm_normal = model_svm_normal.predict(X_test_normal_scaled)
print("SVM - Scaled Normal Data - Test Set Evaluation")
print(confusion_matrix(y_test_normal, y_pred_test_svm_normal))
print(classification_report(y_test_normal, y_pred_test_svm_normal))


SVM - Scaled Normal Data - Validation Set Evaluation
[[1036    0    5]
 [   0 3833    0]
 [   4    1 2342]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221
SVM - Scaled Normal Data - Test Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   2    0 2346]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [45]:
# Scale the log-transformed data
scaler_log = StandardScaler()
X_train_log_scaled = scaler_log.fit_transform(X_train_log)
X_val_log_scaled = scaler_log.transform(X_val_log)
X_test_log_scaled = scaler_log.transform(X_test_log)

# Train SVM on scaled log-transformed data
model_svm_log = SVC(random_state=42)
model_svm_log.fit(X_train_log_scaled, y_train_log)

# Evaluate on Validation Set
y_pred_val_svm_log = model_svm_log.predict(X_val_log_scaled)
print("SVM - Scaled Log-Transformed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_log, y_pred_val_svm_log))
print(classification_report(y_val_log, y_pred_val_svm_log))

# Evaluate on Test Set
y_pred_test_svm_log = model_svm_log.predict(X_test_log_scaled)
print("SVM - Scaled Log-Transformed Data - Test Set Evaluation")
print(confusion_matrix(y_test_log, y_pred_test_svm_log))
print(classification_report(y_test_log, y_pred_test_svm_log))


SVM - Scaled Log-Transformed Data - Validation Set Evaluation
[[1037    0    4]
 [   0 3833    0]
 [   6    0 2341]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221
SVM - Scaled Log-Transformed Data - Test Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   4    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [46]:
# Scale the mixed data (some features log-transformed, some normal)
scaler_mixed = StandardScaler()
X_train_mixed_scaled = scaler_mixed.fit_transform(X_train_mixed)
X_val_mixed_scaled = scaler_mixed.transform(X_val_mixed)
X_test_mixed_scaled = scaler_mixed.transform(X_test_mixed)

# Train SVM on scaled mixed data
model_svm_mixed = SVC(random_state=42)
model_svm_mixed.fit(X_train_mixed_scaled, y_train_mixed)

# Evaluate on Validation Set
y_pred_val_svm_mixed = model_svm_mixed.predict(X_val_mixed_scaled)
print("SVM - Scaled Mixed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_mixed, y_pred_val_svm_mixed))
print(classification_report(y_val_mixed, y_pred_val_svm_mixed))

# Evaluate on Test Set
y_pred_test_svm_mixed = model_svm_mixed.predict(X_test_mixed_scaled)
print("SVM - Scaled Mixed Data - Test Set Evaluation")
print(confusion_matrix(y_test_mixed, y_pred_test_svm_mixed))
print(classification_report(y_test_mixed, y_pred_test_svm_mixed))


SVM - Scaled Mixed Data - Validation Set Evaluation
[[1037    0    4]
 [   0 3833    0]
 [   6    0 2341]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221
SVM - Scaled Mixed Data - Test Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   3    0 2345]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [47]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Scale the normal data
scaler = StandardScaler()
X_train_normal_scaled = scaler.fit_transform(X_train_normal)
X_val_normal_scaled = scaler.transform(X_val_normal)
X_test_normal_scaled = scaler.transform(X_test_normal)

# Train KNN on scaled normal data
model_knn_normal = KNeighborsClassifier(n_neighbors=5)  # You can adjust the number of neighbors
model_knn_normal.fit(X_train_normal_scaled, y_train_normal)

# Evaluate on Validation Set
y_pred_val_knn_normal = model_knn_normal.predict(X_val_normal_scaled)
print("KNN - Scaled Normal Data - Validation Set Evaluation")
print(confusion_matrix(y_val_normal, y_pred_val_knn_normal))
print(classification_report(y_val_normal, y_pred_val_knn_normal))

# Evaluate on Test Set
y_pred_test_knn_normal = model_knn_normal.predict(X_test_normal_scaled)
print("KNN - Scaled Normal Data - Test Set Evaluation")
print(confusion_matrix(y_test_normal, y_pred_test_knn_normal))
print(classification_report(y_test_normal, y_pred_test_knn_normal))


KNN - Scaled Normal Data - Validation Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   3    1 2343]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221
KNN - Scaled Normal Data - Test Set Evaluation
[[1041    0    0]
 [   0 3833    0]
 [   4    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [48]:
# Scale the log-transformed data
scaler_log = StandardScaler()
X_train_log_scaled = scaler_log.fit_transform(X_train_log)
X_val_log_scaled = scaler_log.transform(X_val_log)
X_test_log_scaled = scaler_log.transform(X_test_log)

# Train KNN on scaled log-transformed data
model_knn_log = KNeighborsClassifier(n_neighbors=5)
model_knn_log.fit(X_train_log_scaled, y_train_log)

# Evaluate on Validation Set
y_pred_val_knn_log = model_knn_log.predict(X_val_log_scaled)
print("KNN - Scaled Log-Transformed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_log, y_pred_val_knn_log))
print(classification_report(y_val_log, y_pred_val_knn_log))

# Evaluate on Test Set
y_pred_test_knn_log = model_knn_log.predict(X_test_log_scaled)
print("KNN - Scaled Log-Transformed Data - Test Set Evaluation")
print(confusion_matrix(y_test_log, y_pred_test_knn_log))
print(classification_report(y_test_log, y_pred_test_knn_log))


KNN - Scaled Log-Transformed Data - Validation Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   4    1 2342]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221
KNN - Scaled Log-Transformed Data - Test Set Evaluation
[[1041    0    0]
 [   0 3833    0]
 [   4    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [49]:
# Scale the mixed data (some features log-transformed, some normal)
scaler_mixed = StandardScaler()
X_train_mixed_scaled = scaler_mixed.fit_transform(X_train_mixed)
X_val_mixed_scaled = scaler_mixed.transform(X_val_mixed)
X_test_mixed_scaled = scaler_mixed.transform(X_test_mixed)

# Train KNN on scaled mixed data
model_knn_mixed = KNeighborsClassifier(n_neighbors=5)
model_knn_mixed.fit(X_train_mixed_scaled, y_train_mixed)

# Evaluate on Validation Set
y_pred_val_knn_mixed = model_knn_mixed.predict(X_val_mixed_scaled)
print("KNN - Scaled Mixed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_mixed, y_pred_val_knn_mixed))
print(classification_report(y_val_mixed, y_pred_val_knn_mixed))

# Evaluate on Test Set
y_pred_test_knn_mixed = model_knn_mixed.predict(X_test_mixed_scaled)
print("KNN - Scaled Mixed Data - Test Set Evaluation")
print(confusion_matrix(y_test_mixed, y_pred_test_knn_mixed))
print(classification_report(y_test_mixed, y_pred_test_knn_mixed))


KNN - Scaled Mixed Data - Validation Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   3    1 2343]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221
KNN - Scaled Mixed Data - Test Set Evaluation
[[1041    0    0]
 [   0 3833    0]
 [   4    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [50]:
import lightgbm as lgb
from sklearn.metrics import classification_report, confusion_matrix

# Scale the normal data
scaler = StandardScaler()
X_train_normal_scaled = scaler.fit_transform(X_train_normal)
X_val_normal_scaled = scaler.transform(X_val_normal)
X_test_normal_scaled = scaler.transform(X_test_normal)

# Train LightGBM on scaled normal data
model_lgb_normal = lgb.LGBMClassifier(random_state=42)
model_lgb_normal.fit(X_train_normal_scaled, y_train_normal)

# Evaluate on Validation Set
y_pred_val_lgb_normal = model_lgb_normal.predict(X_val_normal_scaled)
print("LightGBM - Scaled Normal Data - Validation Set Evaluation")
print(confusion_matrix(y_val_normal, y_pred_val_lgb_normal))
print(classification_report(y_val_normal, y_pred_val_lgb_normal))

# Evaluate on Test Set
y_pred_test_lgb_normal = model_lgb_normal.predict(X_test_normal_scaled)
print("LightGBM - Scaled Normal Data - Test Set Evaluation")
print(confusion_matrix(y_test_normal, y_pred_test_lgb_normal))
print(classification_report(y_test_normal, y_pred_test_lgb_normal))


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001144 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 33699, number of used features: 10
[LightGBM] [Info] Start training from score -1.936841
[LightGBM] [Info] Start training from score -0.633450
[LightGBM] [Info] Start training from score -1.123672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LightGBM - Scaled Normal Data - Validation Set Evaluation
[[1035    0    6]
 [   0 3833    0]
 [   

In [51]:
# Scale the log-transformed data
scaler_log = StandardScaler()
X_train_log_scaled = scaler_log.fit_transform(X_train_log)
X_val_log_scaled = scaler_log.transform(X_val_log)
X_test_log_scaled = scaler_log.transform(X_test_log)

# Train LightGBM on scaled log-transformed data
model_lgb_log = lgb.LGBMClassifier(random_state=42)
model_lgb_log.fit(X_train_log_scaled, y_train_log)

# Evaluate on Validation Set
y_pred_val_lgb_log = model_lgb_log.predict(X_val_log_scaled)
print("LightGBM - Scaled Log-Transformed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_log, y_pred_val_lgb_log))
print(classification_report(y_val_log, y_pred_val_lgb_log))

# Evaluate on Test Set
y_pred_test_lgb_log = model_lgb_log.predict(X_test_log_scaled)
print("LightGBM - Scaled Log-Transformed Data - Test Set Evaluation")
print(confusion_matrix(y_test_log, y_pred_test_lgb_log))
print(classification_report(y_test_log, y_pred_test_lgb_log))


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000470 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 33699, number of used features: 10
[LightGBM] [Info] Start training from score -1.936841
[LightGBM] [Info] Start training from score -0.633450
[LightGBM] [Info] Start training from score -1.123672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further spl

In [52]:
# Scale the mixed data (some features log-transformed, some normal)
scaler_mixed = StandardScaler()
X_train_mixed_scaled = scaler_mixed.fit_transform(X_train_mixed)
X_val_mixed_scaled = scaler_mixed.transform(X_val_mixed)
X_test_mixed_scaled = scaler_mixed.transform(X_test_mixed)

# Train LightGBM on scaled mixed data
model_lgb_mixed = lgb.LGBMClassifier(random_state=42)
model_lgb_mixed.fit(X_train_mixed_scaled, y_train_mixed)

# Evaluate on Validation Set
y_pred_val_lgb_mixed = model_lgb_mixed.predict(X_val_mixed_scaled)
print("LightGBM - Scaled Mixed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_mixed, y_pred_val_lgb_mixed))
print(classification_report(y_val_mixed, y_pred_val_lgb_mixed))

# Evaluate on Test Set
y_pred_test_lgb_mixed = model_lgb_mixed.predict(X_test_mixed_scaled)
print("LightGBM - Scaled Mixed Data - Test Set Evaluation")
print(confusion_matrix(y_test_mixed, y_pred_test_lgb_mixed))
print(classification_report(y_test_mixed, y_pred_test_lgb_mixed))


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001328 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 33699, number of used features: 10
[LightGBM] [Info] Start training from score -1.936841
[LightGBM] [Info] Start training from score -0.633450
[LightGBM] [Info] Start training from score -1.123672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LightGBM - Scaled Mixed Data - Validation Set Evaluation
[[1035    0    6]
 [   0 3833    0]
 [   3

In [54]:
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix

# Scale the normal data
scaler = StandardScaler()
X_train_normal_scaled = scaler.fit_transform(X_train_normal)
X_val_normal_scaled = scaler.transform(X_val_normal)
X_test_normal_scaled = scaler.transform(X_test_normal)

# Train XGBoost on scaled normal data
model_xgb_normal = xgb.XGBClassifier(random_state=42, eval_metric='mlogloss')
model_xgb_normal.fit(X_train_normal_scaled, y_train_normal)

# Evaluate on Validation Set
y_pred_val_xgb_normal = model_xgb_normal.predict(X_val_normal_scaled)
print("XGBoost - Scaled Normal Data - Validation Set Evaluation")
print(confusion_matrix(y_val_normal, y_pred_val_xgb_normal))
print(classification_report(y_val_normal, y_pred_val_xgb_normal))

# Evaluate on Test Set
y_pred_test_xgb_normal = model_xgb_normal.predict(X_test_normal_scaled)
print("XGBoost - Scaled Normal Data - Test Set Evaluation")
print(confusion_matrix(y_test_normal, y_pred_test_xgb_normal))
print(classification_report(y_test_normal, y_pred_test_xgb_normal))


XGBoost - Scaled Normal Data - Validation Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   3    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221

XGBoost - Scaled Normal Data - Test Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   2    0 2346]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [55]:
# Scale the log-transformed data
scaler_log = StandardScaler()
X_train_log_scaled = scaler_log.fit_transform(X_train_log)
X_val_log_scaled = scaler_log.transform(X_val_log)
X_test_log_scaled = scaler_log.transform(X_test_log)

# Train XGBoost on scaled log-transformed data
model_xgb_log = xgb.XGBClassifier(random_state=42, eval_metric='mlogloss')
model_xgb_log.fit(X_train_log_scaled, y_train_log)

# Evaluate on Validation Set
y_pred_val_xgb_log = model_xgb_log.predict(X_val_log_scaled)
print("XGBoost - Scaled Log-Transformed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_log, y_pred_val_xgb_log))
print(classification_report(y_val_log, y_pred_val_xgb_log))

# Evaluate on Test Set
y_pred_test_xgb_log = model_xgb_log.predict(X_test_log_scaled)
print("XGBoost - Scaled Log-Transformed Data - Test Set Evaluation")
print(confusion_matrix(y_test_log, y_pred_test_xgb_log))
print(classification_report(y_test_log, y_pred_test_xgb_log))


XGBoost - Scaled Log-Transformed Data - Validation Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   3    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221

XGBoost - Scaled Log-Transformed Data - Test Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   2    0 2346]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222


In [56]:
# Scale the mixed data (some features log-transformed, some normal)
scaler_mixed = StandardScaler()
X_train_mixed_scaled = scaler_mixed.fit_transform(X_train_mixed)
X_val_mixed_scaled = scaler_mixed.transform(X_val_mixed)
X_test_mixed_scaled = scaler_mixed.transform(X_test_mixed)

# Train XGBoost on scaled mixed data
model_xgb_mixed = xgb.XGBClassifier(random_state=42, eval_metric='mlogloss')
model_xgb_mixed.fit(X_train_mixed_scaled, y_train_mixed)

# Evaluate on Validation Set
y_pred_val_xgb_mixed = model_xgb_mixed.predict(X_val_mixed_scaled)
print("XGBoost - Scaled Mixed Data - Validation Set Evaluation")
print(confusion_matrix(y_val_mixed, y_pred_val_xgb_mixed))
print(classification_report(y_val_mixed, y_pred_val_xgb_mixed))

# Evaluate on Test Set
y_pred_test_xgb_mixed = model_xgb_mixed.predict(X_test_mixed_scaled)
print("XGBoost - Scaled Mixed Data - Test Set Evaluation")
print(confusion_matrix(y_test_mixed, y_pred_test_xgb_mixed))
print(classification_report(y_test_mixed, y_pred_test_xgb_mixed))


XGBoost - Scaled Mixed Data - Validation Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   3    0 2344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2347

    accuracy                           1.00      7221
   macro avg       1.00      1.00      1.00      7221
weighted avg       1.00      1.00      1.00      7221

XGBoost - Scaled Mixed Data - Test Set Evaluation
[[1039    0    2]
 [   0 3833    0]
 [   2    0 2346]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1041
           1       1.00      1.00      1.00      3833
           2       1.00      1.00      1.00      2348

    accuracy                           1.00      7222
   macro avg       1.00      1.00      1.00      7222
weighted avg       1.00      1.00      1.00      7222
